### ISSUE TITLE
Banned proxies

### ISSUE THREAD

**Issue by walkero-gr** [Petrprogs/yt-dlp-proxy#1]
Congrats for the nice script. I tested that today but there is a problem with the proxies that are banned from YT. For example, I used it today and got a proxy based in UK, which had the fastest time, but I am getting the following error.

`ERROR: [youtube] r070sTdRt64: Sign in to confirm you’re not a bot. This helps protect our community. Learn more`

If I am not wrong, this means that this proxy is not the best to be used with yt-dlp, and should be skipped.
Maybe there is a need to have a list of banned proxies, which should not be used.
Or, give the user the option to make this list. So, if I see that a server is banned, I could file it in a blacklist file, which will be considered by your script. Furthermore, this file could be exchanged with your server, and then a bigger one can have those banned proxies. I hope I explained that well.

**Comment by Petrprogs** [comment]
Hello, @walkero-gr,
Thanks for sending the isssue! You are right, this error occurs when the ip address of the proxy server seems suspicious to YouTube. But many users use this proxy server, and some of them may pass a bot check in the browser, and YouTube will unban the proxy IP.

**Comment by walkero-gr** [comment]
> But many users use this proxy server, and some of them may pass a bot check in the browser, and YouTube will unban the proxy IP.

Thank you for your reply. I didn't know that this was possible. Do you have any information to share on how this is done, or what should I look for?

**Comment by Petrprogs** [comment]
@walkero-gr 
> These two error codes indicate that the service is blocking your IP address because of overuse. Usually this is a soft block meaning that you can gain access again after solving CAPTCHA. Just open a browser and solve a CAPTCHA the service suggests you

This is part of the answer for solving 429 error form yt-dlp FAQ, but for me it solves (not permanently) "Sings in to confirm..." error too.
