### ISSUE TITLE
Randomise the used proxy

### ISSUE THREAD

**Issue by walkero-gr** [Petrprogs/yt-dlp-proxy#2]
That is not an issue, but mostly an idea. When the proxy list is checked, I would like to propose to store 5/10 of them in the proxy.json file and, every time a call needs to be done, randomly choose one of that list. This way, the requests will not get forwarded to one of them, increasing its usage and possibility to get banned from YT, or any other supported service.

**Comment by Petrprogs** [comment]
Actually, it's a good suggestion :)  In a sense, this enhancement will fix #1, because it will be possible to change the proxy without the need for an `update` command.
