### ISSUE TITLE
ERROR: Failed to parse

### ISSUE THREAD

**Issue by MrGrample** [Petrprogs/yt-dlp-proxy#9]
Hi! I'm trying to setup your script on Windows and the error follows: 

![Scr333eenshot_4](https://github.com/user-attachments/assets/ab994465-1ba0-4569-80ef-ce9095cfc5c1)

I guess something breaks in yt-dlp, but I don't know what exactly. Any ideas?

**Comment by Petrprogs** [comment]
@MrGrample, 
Thank you for submitting this issue.
Seems like yt-dlp ```--proxy``` works a bit different in Windows.

**Comment by Petrprogs** [comment]
Could you try https://github.com/Petrprogs/yt-dlp-proxy/commit/25f533072a48b3f104b0b50343b99cc6ccd4d4a8, please?

**Comment by MrGrample** [comment]
`ERROR: Unable to handle request: Unsupported proxy type: "" (requests, urllib), Unsupported url scheme: "https" (websockets)`

Also I've changed 

`command = f"yt-dlp --color always --proxy 'http://{proxy_str}' {" ".join([str(arg) for arg in sys.argv])} 2>&1 | tee tempout"`

to 

`command = f"yt-dlp --color always --proxy 'http://{proxy_str}' {' '.join([str(arg) for arg in sys.argv])} 2>&1 | tee tempout"`

(notice " " to ' ' change before .join) because otherwise you get a fstring error expecting }

**Comment by Petrprogs** [comment]
> `ERROR: Unable to handle request: Unsupported proxy type: "" (requests, urllib), Unsupported url scheme: "https" (websockets)`
> 
> Also I've changed 
> 
> `command = f"yt-dlp --color always --proxy 'http://{proxy_str}' {" ".join([str(arg) for arg in sys.argv])} 2>&1 | tee tempout"`
> 
> to 
> 
> `command = f"yt-dlp --color always --proxy 'http://{proxy_str}' {' '.join([str(arg) for arg in sys.argv])} 2>&1 | tee tempout"`
> 
> (notice " " to ' ' change before .join) because otherwise you get a fstring error waiting for }

Hmm. Can you print "command" to terminal and execute it yourself?

**Comment by MrGrample** [comment]
Yea, 

`yt-dlp --proxy {proxy_from_your_proxies} {URL} `

works. I now get the "Sign in" error, but it's another deal. 

I used http://vpnfree:rerewtrfsdgdfg@144.126.134.206:14621 as test

**Comment by Petrprogs** [comment]
> Yea, 
> 
> `yt-dlp --proxy {proxy_from_your_proxies} {URL} `
> 
> works. I now get the "Sign in" error, but it's another deal. 
> 
> I used http://vpnfree:rerewtrfsdgdfg@144.126.134.206:14621 as test

Maybe try to remove the quotes from ```command``` that surround the proxy url?

**Comment by MrGrample** [comment]
That helps! Thanks!

**Comment by Petrprogs** [comment]
> That helps! Thanks! 

So, could you make PR, please?

**Comment by MrGrample** [comment]
wdym? I don't have write access to this repository and can't make PR or commits

**Comment by Petrprogs** [comment]
> wdym? I don't have write access to this repository and can't make PR or commits

You can create fork, make your edits there and then create PR to merge branch of your fork to this repo main branch
